theme: jekyll-theme-minimal

remote_theme: academicpages/academicpages.github.io

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-scholar
  
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

title: Weilong Peng ( 彭伟龙 ) - 学术主页

email: "wlpeng@tju.edu.cn; wlpeng@gzhu.edu.cn" 

google_scholar_id: "NAM2GUAAAAJ"

minimal_mistakes_skin: "air"
searc: true
author:
  name: "Weilong Peng"
  avatar: "/peng.jpg"
  location: "广东|广州"

# 首页头像
home:
  image:
    path: /peng.jpg"
    class: "circle"
    width: 200
    height: 200
