theme: jekyll-theme-minimal

remote_theme: academicpages/academicpages.github.io

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-scholar
  
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
include:
  - README.md 
  - peng.jpg



title: Weilong Peng ( 彭伟龙 ) - 学术主页

minimal_mistakes_skin: "air"
searc: true
author:
  name: "Weilong Peng"
  avatar: "/peng.jpg"
  role: "助理教授/硕士生导师" 
  affiliation: "广州大学"
  location: "广东|广州"
  email: "wlpeng@tju.edu.cn"
  links:
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=NAM2GUAAAAJ"



# 首页头像
home:
  image:
    path: "/peng.jpg"
    class: "circle"
    width: 200
    height: 200
