sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass

variables:
  $base-font-size: 18px !default;  # 原来是16px
  $base-line-height: 1.6 !default;  # 原来是1.5
  
  $base-font-family: "Helvetica Neue", Arial, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif !default;
  $heading-font-family: $base-font-family !default;
  
  $h-size-1: 2.5em !default;  # h1
  $h-size-2: 2.0em !default;  # h2
  $h-size-3: 1.75em !default; # h3
  $h-size-4: 1.5em !default;  # h4
  $h-size-5: 1.25em !default; # h5
  $h-size-6: 1.125em !default; # h6
  
  $h-size-1-small: 2.0em !default;
  $h-size-2-small: 1.75em !default;
  $h-size-3-small: 1.5em !default;
  
  $monospace-font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace !default;
  $code-font-size: 0.9em !default;
  
  $nav-font-size: 1.125em !default;
  $nav-link-padding: 0.5em 1em !default;
  
  $footer-font-size: 1em !default;

theme: jekyll-theme-minimal

remote_theme: academicpages/academicpages.github.io

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-scholar
  
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
include:
  - README.md 
  - peng.jpg



title: Weilong Peng ( 彭伟龙 ) - 学术主页

minimal_mistakes_skin: "air"
searc: true
author:
  name: "Weilong Peng"
  avatar: "/peng.jpg"
  role: "助理教授/硕士生导师" 
  affiliation: "广州大学"
  location: "广东|广州"
  email: "wlpeng@tju.edu.cn"
  links:
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=NAM2GUAAAAJ"



# 首页头像
home:
  image:
    path: "/peng.jpg"
    class: "circle"
    width: 200
    height: 200
